### ISSUE TITLE
People can't push to dev-tools repo

### ISSUE THREAD

**Issue by hstewart93** [astro-group-bristol/developer-group#10]
Is this a permissions issue? Andy and I can push

**Comment by fjebaker** [comment]
Ezpz: since you created the repo in the organization, you have admin access on it. Andy and I do too since we're the org admins. So to make it available to everyone in the org with read/write permissions, you need to do:

<img width="1413" alt="Screenshot 2023-12-08 at 17 54 11" src="https://github.com/astro-group-bristol/developer-group/assets/11492844/5307ee6f-7419-4122-821c-a0651e704f06">
<img width="1277" alt="Screenshot 2023-12-08 at 17 54 17" src="https://github.com/astro-group-bristol/developer-group/assets/11492844/1dfa42d4-926b-4f5c-8696-96e21422d7bf">
<img width="1180" alt="Screenshot 2023-12-08 at 17 54 25" src="https://github.com/astro-group-bristol/developer-group/assets/11492844/5e6c1140-dbd3-4614-96c9-c7ea9f747789">
<img width="1303" alt="Screenshot 2023-12-08 at 17 54 36" src="https://github.com/astro-group-bristol/developer-group/assets/11492844/68411c8a-4b33-41dc-8bcc-8f1eb2946820">
